project:
  type: website
  output-dir: docs

website:
  title: "This is a website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Academic Experience.qmd

format:
  html:
    theme: Morph
    css: styles.css
    toc: true



