project:
  type: website
  output-dir: docs

website:
  title: "zhangfan lyu"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - education.qmd
      - projects.qmd
      - Lab 3 notes.qmd
      - Lab_4.qmd

format:
  html:
    theme: Lux
    css: styles.css
    toc: true



