---
title: "Palmer's Penguins"
format: html
editor: visual
execute:
  warning: false
---

## Loading packages

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Dataset overview in a separate window

```{r}
view(penguins)
```

## Playing around with R codes

### The distribution of a single trait

```{r}
penguins %>%
  ggplot() +
  geom_density(mapping = aes(x = bill_length_mm, fill=species), alpha=0.5)
```

```{r}
penguins %>%
  ggplot() +
  geom_histogram(mapping = aes(x = bill_length_mm, fill=species)) +
  facet_wrap(~species, nrow=3)
```

### The relationship between multiple traits

```{r}
penguins %>%
  ggplot(mapping = aes(x = body_mass_g, y=flipper_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="lm")
```

### The level of sexual dimorphism

```{r}
penguins %>%
  ggplot(mapping = aes(x = bill_length_mm, y=bill_depth_mm, color=sex)) +
  geom_point(size=1) +
  facet_wrap(~species)
```

```{r}
penguins %>%
  ggplot(mapping = aes(x=flipper_length_mm, y=sex, color=sex)) +
  geom_boxplot(outlier.alpha = 0, alpha=0) +
  geom_jitter(width = 0, size=1) +
  coord_flip() +
  facet_wrap(~species)
```

### Any temporal trend in the dataset, or patterns within the same species across different islands

```{r}
penguins %>%
  ggplot() +
  geom_bar(mapping = aes(x = year, fill = island)) +
  facet_wrap( ~ species)
```

### color inside aes() vs outside aes()

```{r}
# Every single point will be blue, and no legend is created
ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(color = "blue")
```

```{r}
# The color of the points changes depending on the 'species' column
ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point()
```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_boxplot(aes(color = species), width = 0.3, show.legend = FALSE) +
  geom_jitter(
    aes(color = species),
    alpha = 0.5,
    show.legend = FALSE,
    position = position_jitter(width = 0.2, seed = 0)
  ) +
  scale_color_manual(values = c("plum3", "slateblue3", "turquoise3")) +
  labs(x = "Species", y = "Flipper length (mm)")
```

```{r}
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = sex)) +
  scale_color_manual(values = c("coral3", "darkslategray3"),
                     na.translate = FALSE) +
  labs(
    title = "Penguin flipper and body mass",
    subtitle = "Dimensions for male and female Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
    x = "Flipper length (mm)",
    y = "Body mass (g)",
    color = "Penguin sex"
  ) +
  theme(
    legend.position = "bottom",
    plot.title.position = "plot",
    plot.caption = element_text(hjust = 0, face = "italic"),
    plot.caption.position = "plot"
  ) +
  facet_wrap( ~ species)
```

```{r}
ggplot(data = penguins, 
       aes(x = body_mass_g, y = flipper_length_mm, color = species)) +
  geom_point(alpha = 0.4) +
  geom_smooth()
```
